version: "3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  web:
    depends_on:
      - mysql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST_IP=mysql
volumes:
  mysql: